"""
certkit-cpo -- Hamiltonian *families* for the fill-reducing-ordering harness.

Every family is a function f(scale) -> (n, masks) where

    scale == q == the qubit count, and n == 1 << q, ALWAYS.

`masks` is a sorted list of DISTINCT NONZERO ints < n: the set of bit-flip
masks of the Pauli terms.  Per the session-6 result these masks are the only
thing that matters for sparsity: the operator's sparsity graph is exactly the
Cayley graph on Z_2^q generated by them (vertex i -- i^m).  Diagonal (Z-only,
mask 0) terms are dropped because they contribute no edges and no fill.

Connectivity note (IMPORTANT, read before averaging anything):
Only `hypercube_tfim` and `random_k_local` produce CONNECTED Cayley graphs.
Every other family here is generated exclusively by EVEN-Hamming-weight masks
(two-site XX couplings; JW/BK one- and two-body fermionic terms), so its
generators span a subgroup of the even-weight subspace and the graph splits
into exactly 2 components -- the even- and odd-Hamming-weight halves.  That is
not a bug: for the fermionic families it is fermion-parity superselection, and
for the pure-XX lattice families it is the same Z_2 parity.  Consequence for
the experiment: each such family is really two independent n/2-vertex
elimination problems, and ops/n^3 for it is ~1/4 of the ops/(n/2)^3 you would
measure on a single sector.  Compare across families accordingly; the
self-check prints the component count for each (family, q) so this can never be
silently averaged in.

Degeneracy note: `jw_one_body` and `all_to_all` produce IDENTICAL generator
sets for every q (a dense one-body h_pq contributes a p<->q bit-flip mask for
every pair, which is precisely the all-to-all XX generator set), and
`bravyi_kitaev` is `jw_one_body` under an invertible GF(2) relabelling, so its
graph is isomorphic.  Those three are one structural data point, not three.
`lattice_2d` degenerates to `chain_1d_nn` whenever q is prime.

Python 3.12 stdlib only.  No numpy, no third-party imports.
"""

import importlib.util
import math
import os
import random
from itertools import combinations

# ---------------------------------------------------------------- JW transform

# Session-5 JW transform lives one directory up, in sandbox-handoffs/. Resolved
# relative to this file so the sweep stays rerunnable if the repo moves.
_JW_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "certkit-ph1-jw-termcount-experiment.py",
)
_spec = importlib.util.spec_from_file_location(
    "certkit_ph1_jw_termcount_experiment", _JW_PATH
)
jwmod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(jwmod)


def jw_masks(M, seed=1, two_body=True):
    """Distinct nonzero bit-flip masks appearing in a random JW-mapped
    one(+two)-body electronic-structure-shaped Hamiltonian on M qubits.

    Copied verbatim from certkit-ph1-fillreducing-experiment.py (session 6) so
    the numbers stay comparable; `two_body` is passed through unchanged."""
    rng = random.Random(seed)
    acc = {}
    h1 = [[0.0] * M for _ in range(M)]
    for p in range(M):
        for q_ in range(p, M):
            v = rng.uniform(-1, 1)
            h1[p][q_] = v
            h1[q_][p] = v
    for p in range(M):
        for q_ in range(M):
            if h1[p][q_] == 0.0:
                continue
            terms = jwmod.mul_terms(jwmod.jw_ladder(p, M, True), jwmod.jw_ladder(q_, M, False))
            jwmod.add_into(acc, terms, h1[p][q_])
    if two_body:
        seen = {}
        for p in range(M):
            for q_ in range(M):
                for r in range(M):
                    for s in range(M):
                        if p == q_ or r == s:
                            continue
                        canon = min((p, q_, r, s), (q_, p, s, r))
                        if canon not in seen:
                            seen[canon] = rng.uniform(-1, 1)
                        v = seen[canon]
                        if (p, q_, r, s) not in [canon, (canon[1], canon[0], canon[3], canon[2])]:
                            continue
                        if v == 0.0:
                            continue
                        terms = jwmod.mul_terms(
                            jwmod.mul_terms(jwmod.jw_ladder(p, M, True), jwmod.jw_ladder(q_, M, True)),
                            jwmod.mul_terms(jwmod.jw_ladder(r, M, False), jwmod.jw_ladder(s, M, False)),
                        )
                        jwmod.add_into(acc, terms, 0.5 * v)
    masks = set()
    for s, c in acc.items():
        if abs(c) <= 1e-9:
            continue
        mask = 0
        for k, ch in enumerate(s):
            if ch in ("X", "Y"):
                mask |= 1 << k
        if mask:
            masks.add(mask)
    return sorted(masks)


# ------------------------------------------------------- Bravyi-Kitaev encoding

def bk_occupation_set(i):
    """Fenwick-tree occupation set of BK qubit i: the orbital indices whose
    occupations qubit i stores the parity of.  Binary-indexed-tree node i+1
    (1-based) covers the contiguous 1-based range (i+1-lowbit(i+1), i+1], i.e.
    the 0-based range [i+1-lowbit(i+1), i].  Textbook values for q=8:
    {0}, {0,1}, {2}, {0,1,2,3}, {4}, {4,5}, {6}, {0..7}."""
    idx = i + 1
    return set(range(idx - (idx & -idx), idx))


def bk_beta(q):
    """The BK encoding matrix beta as a list of q ints: row i is the bitmask of
    orbitals summed (mod 2) into qubit i.  Unit lower triangular over GF(2),
    hence invertible."""
    return [sum(1 << j for j in bk_occupation_set(i)) for i in range(q)]


def bk_apply(beta, v):
    """Apply beta to an occupation-basis vector v (as a bitmask) over GF(2)."""
    out = 0
    for i, row in enumerate(beta):
        if bin(row & v).count("1") & 1:
            out |= 1 << i
    return out


def bk_masks(q, seed=1, two_body=False):
    """Bit-flip masks of the BK-mapped Hamiltonian.

    Derived exactly, not re-derived term by term.  BK differs from JW only by a
    relabelling of the computational basis: |f> (occupation) is stored as
    |beta f>, and beta is an invertible GF(2)-linear map.  A matrix entry
    (f, f') therefore lands at (beta f, beta f'), so the set of bit-flip masks
    -- the set of differences f ^ f' over nonzero entries -- becomes
    {beta(m) : m in JW masks} by linearity of beta.  No cancellations can
    differ between the two encodings because the map is an exact permutation
    similarity of the same matrix.

    KEY CONSEQUENCE: the BK sparsity graph is *isomorphic* to the JW one (a
    linear automorphism of Z_2^q carries the Cayley graph to the Cayley graph
    on the image generators).  Fill-in and op counts under an optimal ordering
    are therefore identical; only heuristics that read vertex labels can differ.
    """
    beta = bk_beta(q)
    return sorted({bk_apply(beta, m) for m in jw_masks(q, seed=seed, two_body=two_body)})


# ------------------------------------------------------------------- families

def hypercube_tfim(q):
    """TFIM / transverse field: one X per qubit -> the q-cube Q_q."""
    return 1 << q, sorted(1 << k for k in range(q))


def chain_1d_nn(q):
    """1D nearest-neighbour XX coupling, open boundary.

    Deliberately PURE two-site: the single-site X masks are NOT included, so
    the generator set is genuinely different from hypercube_tfim rather than a
    superset of it.  Price of that choice: all generators have even Hamming
    weight, so the graph has 2 components (see module docstring)."""
    return 1 << q, sorted((1 << k) | (1 << (k + 1)) for k in range(q - 1))


def _square_factor(q):
    """Most square factorisation r*c = q with r <= c.  For prime q this returns
    (1, q), i.e. the lattice degenerates to a 1 x q open chain -- said out loud
    here rather than hidden, since for prime q lattice_2d == chain_1d_nn."""
    r = max(d for d in range(1, int(math.isqrt(q)) + 1) if q % d == 0)
    return r, q // r


def lattice_2d(q):
    """2D square lattice XX coupling, r x c grid with r*c = q, open boundary.
    Qubit index = row*c + col.  Prime q falls back to a 1 x q chain."""
    r, c = _square_factor(q)
    masks = set()
    for i in range(r):
        for j in range(c):
            v = i * c + j
            if j + 1 < c:
                masks.add((1 << v) | (1 << (v + 1)))
            if i + 1 < r:
                masks.add((1 << v) | (1 << (v + c)))
    return 1 << q, sorted(masks)


def all_to_all(q):
    """XX coupling on every pair of qubits."""
    return 1 << q, sorted((1 << i) | (1 << j) for i in range(q) for j in range(i + 1, q))


def random_k_local(q, k=3, seed=None):
    """Random k-local (k=3) terms: min(4q, C(q,k)) distinct k-subsets, mask =
    OR of their bits.  Seed depends only on q, so this is reproducible."""
    rng = random.Random(20250830 + q if seed is None else seed)
    pool = list(combinations(range(q), k))
    chosen = pool if len(pool) <= 4 * q else rng.sample(pool, 4 * q)
    return 1 << q, sorted(sum(1 << b for b in c) for c in chosen)


def jw_one_body(q):
    return 1 << q, jw_masks(q, seed=1, two_body=False)


def jw_two_body(q):
    return 1 << q, jw_masks(q, seed=1, two_body=True)


def bravyi_kitaev(q):
    """BK analogue of jw_one_body.  See bk_masks: isomorphic graph, by design."""
    return 1 << q, bk_masks(q, seed=1, two_body=False)


FAMILIES = {
    "hypercube_tfim": hypercube_tfim,
    "chain_1d_nn": chain_1d_nn,
    "lattice_2d": lattice_2d,
    "all_to_all": all_to_all,
    "random_k_local": random_k_local,
    "jw_one_body": jw_one_body,
    "jw_two_body": jw_two_body,
    "bravyi_kitaev": bravyi_kitaev,
}

# Components of the Cayley graph, asserted by the self-check.  1 = connected.
# 2 = the even/odd-Hamming-weight split forced by all-even-weight generators.
EXPECTED_COMPONENTS = {
    "hypercube_tfim": 1,
    "chain_1d_nn": 2,
    "lattice_2d": 2,
    "all_to_all": 2,
    "random_k_local": 1,
    "jw_one_body": 2,
    "jw_two_body": 2,
    "bravyi_kitaev": 2,
}


def n_components(n, masks):
    """Number of connected components of the Cayley graph, by BFS over i -> i^m."""
    seen = [False] * n
    comps = 0
    for start in range(n):
        if seen[start]:
            continue
        comps += 1
        seen[start] = True
        frontier = [start]
        while frontier:
            nxt = []
            for i in frontier:
                for m in masks:
                    j = i ^ m
                    if not seen[j]:
                        seen[j] = True
                        nxt.append(j)
            frontier = nxt
    return comps


# ------------------------------------------------------------------ self-check

if __name__ == "__main__":
    fails = []

    def check(cond, msg):
        if cond:
            print(f"PASS  {msg}")
        else:
            print(f"FAIL  {msg}")
            fails.append(msg)

    # BK Fenwick occupation sets against the textbook values.
    check(
        [sorted(bk_occupation_set(i)) for i in range(8)]
        == [[0], [0, 1], [2], [0, 1, 2, 3], [4], [4, 5], [6], [0, 1, 2, 3, 4, 5, 6, 7]],
        "bk_occupation_set matches the standard Fenwick sets for q=8",
    )
    _beta = bk_beta(6)
    check(
        all((_beta[i] >> i) & 1 and _beta[i] < (2 << i) for i in range(6)),
        "bk_beta is unit lower triangular over GF(2) (hence invertible)",
    )
    check(
        len({bk_apply(_beta, v) for v in range(64)}) == 64,
        "bk_beta acts bijectively on Z_2^6",
    )

    print()
    hdr = f"{'family':>16} {'q':>3} {'n':>6} {'#masks':>7} {'degree':>7} {'comps':>6}  {'note':<28}"
    print(hdr)
    print("-" * len(hdr))
    disconnected = set()
    for name, fn in FAMILIES.items():
        for q in range(4, 11):
            n, masks = fn(q)
            ok = (
                n == 1 << q
                and len(set(masks)) == len(masks)
                and masks == sorted(masks)
                and all(0 < m < n for m in masks)
            )
            if not ok:
                fails.append(f"{name} q={q} mask invariants")
            comps = n_components(n, masks)
            if comps != EXPECTED_COMPONENTS[name]:
                fails.append(f"{name} q={q} components {comps} != {EXPECTED_COMPONENTS[name]}")
            if comps > 1:
                disconnected.add(name)
            note = ""
            if name == "lattice_2d":
                note = "grid %dx%d" % _square_factor(q)
            elif comps > 1:
                note = "DISCONNECTED"
            print(f"{name:>16} {q:>3} {n:>6} {len(masks):>7} {len(masks):>7} {comps:>6}  {note:<28}")

    print()
    check(not any(f.endswith("mask invariants") for f in fails),
          "all families: masks distinct, nonzero, < 1<<q, sorted, for q=4..10")
    check(not any("components" in f for f in fails),
          "all families: component count matches EXPECTED_COMPONENTS for q=4..10")

    # BK really is a relabelling of JW: same #masks, same degree, same comps.
    same = all(
        len(bravyi_kitaev(q)[1]) == len(jw_one_body(q)[1]) for q in range(4, 11)
    )
    check(same, "bravyi_kitaev has the same generator count as jw_one_body (beta is a bijection)")
    check(bravyi_kitaev(6)[1] != jw_one_body(6)[1],
          "bravyi_kitaev generators genuinely differ from jw_one_body's at q=6")

    # Determinism.
    check(random_k_local(9)[1] == random_k_local(9)[1] and jw_two_body(6)[1] == jw_two_body(6)[1],
          "families are deterministic across repeated calls")

    print()
    print("LOUD NOTE -- disconnected sparsity graphs (2 components each, the")
    print("even/odd-Hamming-weight split forced by all-even-weight generators):")
    print("  " + ", ".join(sorted(disconnected)))
    print("  These are two independent n/2-vertex elimination problems, NOT one")
    print("  n-vertex problem. Do not average their ops/n^3 against hypercube_tfim")
    print("  or random_k_local without dividing out the sector split.")
    dup = all(jw_one_body(q)[1] == all_to_all(q)[1] for q in range(4, 11))
    print("LOUD NOTE -- jw_one_body and all_to_all are the SAME generator set" if dup
          else "NOTE -- jw_one_body and all_to_all differ")
    print("  (a dense one-body h_pq gives a p<->q bit-flip mask for every pair, which is")
    print("  exactly the all-to-all XX generator set). They are ONE data point, not two.")
    print("NOTE -- bravyi_kitaev is included, and is EXACT: BK = JW composed with an")
    print("  invertible GF(2) basis change beta, so its masks are beta(JW masks) and")
    print("  its Cayley graph is ISOMORPHIC to jw_one_body's. Any difference the")
    print("  harness measures is a heuristic's label-sensitivity, not real structure.")

    print()
    print("FAIL" if fails else "PASS", f"-- {len(fails)} failing check(s)")
