"""
Shared harness for the certkit-cpo fill-reducing-ordering experiment.

Sparsity-graph fact (established, see certkit-ph1 session 6): a PauliSumReal
term with bit-flip mask m connects basis state i to i^m for every i, so the
operator's sparsity graph on n = 2^q basis states is exactly the Cayley graph
on Z_2^q generated by the distinct nonzero masks.  Diagonal (mask=0) terms
contribute no edges.

This module provides the three primitives every ordering module in the harness
shares:

    build_adj(n, masks)                       -- the Cayley-graph adjacency
    min_degree_fill(n, masks, time_budget_s)  -- session-6's greedy min-degree
                                                 elimination, copied VERBATIM
                                                 (regression anchor: its
                                                 published numbers must
                                                 reproduce byte-identically)
    eliminate_with_perm(n, masks, perm, ...)  -- the same elimination driven by
                                                 a fixed pivot order instead of
                                                 the greedy choice

Stdlib only (no numpy/scipy), deterministic.  Run this file directly for its
self-check.
"""
import random
import time


def build_adj(n, masks):
    """Adjacency (list of sets) of the Cayley graph on Z_2^q generated by
    `masks`.  adj[i] never contains i itself."""
    adj = [set() for _ in range(n)]
    for i in range(n):
        for m in masks:
            adj[i].add(i ^ m)
    for i in range(n):
        adj[i].discard(i)
    return adj


# --- VERBATIM from certkit-ph1-fillreducing-experiment.py (session 6). -------
# Do not "improve" this: session 6's published numbers are the regression
# anchor for the whole experiment.

def min_degree_fill(n, masks, time_budget_s=25.0):
    """Greedy minimum-degree symbolic elimination on the Cayley graph
    generated by `masks` over Z_2^{log2 n}. Returns (total_fill_edges,
    total_op_proxy, max_degree_seen, completed) where completed is False if
    the time budget ran out (partial result, honestly reported as such)."""
    adj = [set() for _ in range(n)]
    for i in range(n):
        for m in masks:
            adj[i].add(i ^ m)
    for i in range(n):
        adj[i].discard(i)

    remaining = set(range(n))
    total_fill = 0
    total_ops = 0
    max_deg = 0
    t0 = time.time()
    completed = True
    steps = 0
    while remaining:
        if time.time() - t0 > time_budget_s:
            completed = False
            break
        v = min(remaining, key=lambda x: len(adj[x]))
        nbrs = [u for u in adj[v] if u in remaining]
        d = len(nbrs)
        max_deg = max(max_deg, d)
        total_ops += d * d
        for i in range(len(nbrs)):
            a = nbrs[i]
            for j in range(i + 1, len(nbrs)):
                b = nbrs[j]
                if b not in adj[a]:
                    adj[a].add(b)
                    adj[b].add(a)
                    total_fill += 1
        for u in nbrs:
            adj[u].discard(v)
        remaining.discard(v)
        steps += 1
    return total_fill, total_ops, max_deg, completed, steps

# --- end verbatim block -----------------------------------------------------


def eliminate_with_perm(n, masks, perm, time_budget_s=120.0):
    """Perm-driven twin of min_degree_fill: identical bookkeeping, the pivot is
    taken from `perm` instead of chosen greedily.  Returns
    (total_fill, total_ops, max_deg, completed, steps).

    `perm` MUST be a permutation of range(n).  A short or duplicate-bearing perm
    silently under-counts ops and still reports completed=True, which would make
    a buggy ordering module look artificially sub-cubic -- so it is rejected."""
    perm = list(perm)
    if len(perm) != n or set(perm) != set(range(n)):
        raise ValueError(
            f"perm is not a permutation of range({n}): len={len(perm)}, "
            f"distinct={len(set(perm))}, missing={len(set(range(n)) - set(perm))}")
    adj = build_adj(n, masks)

    remaining = set(range(n))
    total_fill = 0
    total_ops = 0
    max_deg = 0
    t0 = time.time()
    completed = True
    steps = 0
    for v in perm:
        if time.time() - t0 > time_budget_s:
            completed = False
            break
        nbrs = [u for u in adj[v] if u in remaining]
        d = len(nbrs)
        max_deg = max(max_deg, d)
        total_ops += d * d
        for i in range(len(nbrs)):
            a = nbrs[i]
            for j in range(i + 1, len(nbrs)):
                b = nbrs[j]
                if b not in adj[a]:
                    adj[a].add(b)
                    adj[b].add(a)
                    total_fill += 1
        for u in nbrs:
            adj[u].discard(v)
        remaining.discard(v)
        steps += 1
    return total_fill, total_ops, max_deg, completed, steps


def _min_degree_fill_recording(n, masks, time_budget_s=25.0):
    """min_degree_fill with the pivot sequence recorded.  Used only by the
    self-check, to prove eliminate_with_perm agrees with the greedy path."""
    adj = build_adj(n, masks)
    remaining = set(range(n))
    total_fill = 0
    total_ops = 0
    max_deg = 0
    t0 = time.time()
    completed = True
    steps = 0
    pivots = []
    while remaining:
        if time.time() - t0 > time_budget_s:
            completed = False
            break
        v = min(remaining, key=lambda x: len(adj[x]))
        pivots.append(v)
        nbrs = [u for u in adj[v] if u in remaining]
        d = len(nbrs)
        max_deg = max(max_deg, d)
        total_ops += d * d
        for i in range(len(nbrs)):
            a = nbrs[i]
            for j in range(i + 1, len(nbrs)):
                b = nbrs[j]
                if b not in adj[a]:
                    adj[a].add(b)
                    adj[b].add(a)
                    total_fill += 1
        for u in nbrs:
            adj[u].discard(v)
        remaining.discard(v)
        steps += 1
    return total_fill, total_ops, max_deg, completed, steps, pivots


def _reference_eliminate(n, masks, perm):
    """Deliberately slow, obviously-correct reference: boolean adjacency
    matrix, no sets, no cleverness.  For n <= 16 only."""
    A = [[False] * n for _ in range(n)]
    for i in range(n):
        for m in masks:
            j = i ^ m
            if j != i:
                A[i][j] = True
                A[j][i] = True
    alive = [True] * n
    fill = 0
    ops = 0
    maxd = 0
    for v in perm:
        nbrs = [u for u in range(n) if alive[u] and u != v and A[v][u]]
        ops += len(nbrs) ** 2
        maxd = max(maxd, len(nbrs))
        for a in nbrs:
            for b in nbrs:
                if a < b and not A[a][b]:
                    A[a][b] = True
                    A[b][a] = True
                    fill += 1
        alive[v] = False
    return fill, ops, maxd


if __name__ == "__main__":
    # 1. build_adj on the q=3 hypercube.
    adj = build_adj(8, [1, 2, 4])
    for i in range(8):
        assert adj[i] == {i ^ 1, i ^ 2, i ^ 4}, (i, adj[i])
        assert len(adj[i]) == 3
    print("PASS 1: build_adj gives Q_3 (every vertex degree 3, adj[i]=={i^1,i^2,i^4})")

    # 2. Equivalence anchor: greedy pivot order replayed through
    #    eliminate_with_perm must reproduce the greedy stats exactly.
    cases = [
        (8, [1, 2, 4]),
        (16, [1, 2, 4, 8]),
        (16, [1, 3, 5]),
        (32, [1, 2, 4, 8, 16]),
        (32, [3, 5, 6, 12]),
        (64, [1, 2, 4, 8, 16, 32]),
        (64, [1, 7, 21, 42]),
        (256, [1, 2, 4, 8, 16, 32, 64, 128]),
    ]
    rng = random.Random(20260830)
    for q in (4, 5, 6):
        for _ in range(4):
            n = 1 << q
            k = rng.randint(1, q + 2)
            ms = sorted(set(rng.randrange(1, n) for _ in range(k)))
            cases.append((n, ms))
    for n, ms in cases:
        f0, o0, d0, c0, s0, pivots = _min_degree_fill_recording(n, ms, 60.0)
        assert c0 and s0 == n
        assert sorted(pivots) == list(range(n))
        f1, o1, d1, c1, s1 = eliminate_with_perm(n, ms, pivots, 60.0)
        assert c1 and s1 == n
        assert (f0, o0, d0) == (f1, o1, d1), (n, ms, (f0, o0, d0), (f1, o1, d1))
        # and the verbatim function agrees with its recording twin
        assert min_degree_fill(n, ms, 60.0)[:3] == (f0, o0, d0)
    print(f"PASS 2: greedy-order replay matches min_degree_fill on {len(cases)} graphs "
          "(fill, ops, max_deg identical)")

    # 3. Brute-force reference on n <= 16, random masks and random perms.
    rng = random.Random(4242)
    checked = 0
    for _ in range(40):
        q = rng.choice([2, 3, 4])
        n = 1 << q
        ms = sorted(set(rng.randrange(1, n) for _ in range(rng.randint(1, n - 1))))
        perm = list(range(n))
        if checked % 3:
            rng.shuffle(perm)
        got = eliminate_with_perm(n, ms, perm, 60.0)
        exp = _reference_eliminate(n, ms, perm)
        assert got[:3] == exp, (n, ms, perm, got, exp)
        assert got[3] and got[4] == n
        checked += 1
    assert checked >= 20
    print(f"PASS 3: matches brute-force adjacency-matrix reference on {checked} "
          "(masks, perm) cases")

    # 4. K_8 sanity: n=8, all nonzero masks -> complete graph, no fill.
    n = 8
    ms = list(range(1, 8))
    expect_ops = sum((n - 1 - k) ** 2 for k in range(n))
    for perm in (list(range(n)), [3, 0, 7, 1, 5, 2, 6, 4]):
        f, o, d, c, s = eliminate_with_perm(n, ms, perm, 60.0)
        assert (f, o, d, c, s) == (0, expect_ops, n - 1, True, n), (perm, f, o, d)
    f, o, d, c, s = min_degree_fill(n, ms, 60.0)
    assert (f, o) == (0, expect_ops)
    print(f"PASS 4: K_8 gives fill=0, ops={expect_ops} (= sum (n-1-k)^2) for both paths")

    # 5. Non-permutation input must raise, not silently under-count.
    bad = [
        list(range(8)),              # too short for n=16
        [0] * 16,                    # duplicates, right length
        list(range(16)) + [3],       # too long
        [i + 1 for i in range(16)],  # right length/distinct, out of range
    ]
    for p in bad:
        try:
            eliminate_with_perm(16, [1, 2, 4, 8], p, 60.0)
        except ValueError:
            pass
        else:
            raise AssertionError(f"non-permutation accepted: {p[:5]}... len={len(p)}")
    # ...and a real permutation still works
    assert eliminate_with_perm(16, [1, 2, 4, 8], list(range(16)), 60.0)[3]
    print(f"PASS 5: eliminate_with_perm rejects all {len(bad)} non-permutation inputs "
          "(short / duplicate / long / out-of-range)")
