"""
ord_amd.py -- APPROXIMATE MINIMUM DEGREE (AMD) ordering for certkit-cpo.

Contract exception
------------------
AMD is a *dynamic* ordering: the pivot chosen at step k depends on the fill
already created by steps 0..k-1, so it cannot be precomputed as a static
permutation of the input graph.  Per the task spec this module therefore runs
the symbolic elimination itself (on a quotient graph, which is cheap) and
returns the pivot sequence it actually used.  Feeding that sequence back into
harness.eliminate_with_perm reproduces AMD's own operation count exactly --
asserted in the self-check below.

What is implemented
-------------------
The real Amestoy-Davis-Duff quotient-graph formulation:

  * Variables and elements.  Each still-uneliminated variable i carries
    A[i] (adjacent *variables*) and E[i] (adjacent *elements*).  Eliminating
    pivot p turns p into an element with element list

        Lp = (A[p] u  U_{e in E[p]} Le)  minus {p},  restricted to live vars

    which is *exactly* the set of neighbours of p in the current filled
    (elimination) graph -- no fill edges are ever materialised.
  * Element absorption: every e in E[p] is absorbed into p and deleted, so
    the quotient graph stays O(|A| + n) sized rather than blowing up to the
    dense filled graph.
  * Adjacency pruning: A[i] -= Lp for i in Lp (those edges are now carried
    by element p).
  * Approximate external degree, the standard AMD bound (Amestoy, Davis &
    Duff 1996, "An approximate minimum degree ordering algorithm", eq. (3);
    Davis, "Direct Methods for Sparse Linear Systems", eq. 7.3):

        d_i <- min( n - k,
                    d_i + |Lp \\ Li|,
                    |A_i \\ i| + |Lp \\ i| + sum_{e in E_i \\ {p}} |Le \\ Lp| )

    Two notes on the exact form used here:
      - the middle term is evaluated with the looser but still valid
        |Lp \\ i| in place of |Lp \\ Li| (|Lp \\ Li| <= |Lp \\ i| always, so
        the bound stays an upper bound; dropping Li just avoids carrying the
        previous element list).  This is the same simplification most
        textbook write-ups of AMD make.
      - the |Le \\ Lp| terms are computed by the standard O(sum |E_i|) "w
        array" sweep: w[e] starts at |Le| and is decremented once per
        i in Lp with e in E[i], leaving w[e] = |Le \\ Lp|.
  * "n - k" is taken as (number of live variables) - 1, the tight version.

LIMITATION -- no supervariables
-------------------------------
This is a *reduced* AMD: it has the quotient graph, element absorption and
the approximate degree, but NOT supervariable / indistinguishable-node
detection (and therefore no mass elimination and no aggressive absorption).
Supervariables are a speed-and-tie-breaking device in AMD, not a separate
ordering heuristic, so their absence changes tie-breaking and runtime, not
the character of the ordering.  This is stated here rather than hidden: the
module is an honest reduced AMD, not exact minimum degree wearing a hat.

What AMD can and cannot buy this experiment
-------------------------------------------
AMD is an approximation OF minimum degree, engineered to be FASTER to
compute -- it is not designed to produce *better* orderings, and generally
produces slightly worse ones.  Session 6 already measured exact greedy
minimum degree on these graphs and found ops/n^3 converging to a constant
(~0.026 hypercube, ~0.08 JW two-body), i.e. cubic.  So the scientifically
useful outcome here is NOT "AMD beats min-degree" -- that would be surprising
enough to be suspicious -- but "AMD lands within a small constant factor of
exact min-degree", which cross-validates both measurements and rules out the
possibility that session 6's min-degree implementation was the thing making
the cost cubic.  The self-check asserts that agreement (factor of 3) so that
a buggy AMD cannot quietly pass as a result.
"""

import time

NAME = "amd"


def _build_adj(n, masks):
    """Cayley graph on Z_2^q generated by `masks`; adj[i] excludes i."""
    gens = sorted({m for m in masks if m})
    adj = [set() for _ in range(n)]
    for i in range(n):
        s = adj[i]
        for m in gens:
            s.add(i ^ m)
        s.discard(i)
    return adj


def order_with_stats(n, masks, time_budget_s=120.0):
    """Run reduced AMD symbolically.

    Returns (perm, total_ops, max_deg, completed, steps) where total_ops is
    sum of |Lp|^2 over pivots -- |Lp| is the *exact* external degree of the
    pivot in the elimination graph (the quotient graph represents it
    exactly; only the *selection* metric is approximate), so this must match
    harness.eliminate_with_perm(n, masks, perm)[1] when AMD completes.

    On time-budget exhaustion the remaining variables are appended in
    ascending order so the result is still a valid permutation, and
    completed=False is returned.  total_ops then covers only the `steps`
    pivots AMD actually chose.
    """
    A = _build_adj(n, masks)
    E = [set() for _ in range(n)]
    Le = {}
    live = set(range(n))
    deg = [len(A[i]) for i in range(n)]

    perm = []
    total_ops = 0
    max_deg = 0
    completed = True
    t0 = time.time()

    while live:
        if time.time() - t0 > time_budget_s:
            completed = False
            break

        p = min(live, key=lambda i: (deg[i], i))
        live.discard(p)

        # ---- form the element list Lp = true neighbourhood of p ----
        Ep = list(E[p])          # snapshot: absorption below mutates E[p]
        Lp = set(A[p])
        for e in Ep:
            Lp |= Le[e]
        Lp &= live
        Lp.discard(p)

        # ---- element absorption: every e in E[p] is subsumed by p ----
        for e in Ep:
            for i in Le[e]:
                E[i].discard(e)
            del Le[e]
        A[p] = set()
        E[p] = set()

        d = len(Lp)
        max_deg = max(max_deg, d)
        total_ops += d * d
        perm.append(p)
        Le[p] = Lp

        # ---- quotient-graph update ----
        for i in Lp:
            A[i] -= Lp          # those edges are now carried by element p
            A[i].discard(p)
            E[i].add(p)

        # ---- w[e] = |Le \ Lp| by the standard sweep ----
        w = {}
        for i in Lp:
            for e in E[i]:
                if e != p:
                    w[e] = w.get(e, len(Le[e])) - 1

        cap = len(live) - 1
        for i in Lp:
            b2 = deg[i] + d - 1                     # d_i + |Lp \ i|
            b3 = len(A[i]) + (d - 1)
            for e in E[i]:
                if e != p:
                    b3 += w[e]
            deg[i] = min(cap, b2, b3)

    steps = len(perm)
    if not completed:
        perm.extend(sorted(live))
    return perm, total_ops, max_deg, completed, steps


def order(n, masks, time_budget_s=120.0):
    """Contract entry point: the pivot sequence AMD used, as a permutation."""
    return order_with_stats(n, masks, time_budget_s)[0]


# --------------------------------------------------------------------------
# self-check
# --------------------------------------------------------------------------
if __name__ == "__main__":
    try:
        from harness import build_adj, eliminate_with_perm, min_degree_fill
    except ImportError:  # harness.py not written yet by the sibling agent
        def build_adj(n, masks):
            return _build_adj(n, masks)

        def eliminate_with_perm(n, masks, perm, time_budget_s=120.0):
            adj = build_adj(n, masks)
            remaining = set(range(n))
            total_fill = total_ops = max_deg = steps = 0
            t0 = time.time()
            for v in perm:
                if time.time() - t0 > time_budget_s:
                    return total_fill, total_ops, max_deg, False, steps
                nbrs = [u for u in adj[v] if u in remaining]
                d = len(nbrs)
                max_deg = max(max_deg, d)
                total_ops += d * d
                for i in range(len(nbrs)):
                    a = nbrs[i]
                    for j in range(i + 1, len(nbrs)):
                        b = nbrs[j]
                        if b not in adj[a]:
                            adj[a].add(b)
                            adj[b].add(a)
                            total_fill += 1
                for u in nbrs:
                    adj[u].discard(v)
                remaining.discard(v)
                steps += 1
            return total_fill, total_ops, max_deg, True, steps

        def min_degree_fill(n, masks, time_budget_s=25.0):
            adj = build_adj(n, masks)
            remaining = set(range(n))
            total_fill = total_ops = max_deg = steps = 0
            t0 = time.time()
            completed = True
            while remaining:
                if time.time() - t0 > time_budget_s:
                    completed = False
                    break
                v = min(remaining, key=lambda x: len(adj[x]))
                nbrs = [u for u in adj[v] if u in remaining]
                d = len(nbrs)
                max_deg = max(max_deg, d)
                total_ops += d * d
                for i in range(len(nbrs)):
                    a = nbrs[i]
                    for j in range(i + 1, len(nbrs)):
                        b = nbrs[j]
                        if b not in adj[a]:
                            adj[a].add(b)
                            adj[b].add(a)
                            total_fill += 1
                for u in nbrs:
                    adj[u].discard(v)
                remaining.discard(v)
                steps += 1
            return total_fill, total_ops, max_deg, completed, steps

        print("NOTE: harness.py not importable; using local stub for self-check.")

    ok = True

    def check(label, cond):
        global ok
        print(f"{'PASS' if cond else 'FAIL'}: {label}")
        ok = ok and cond

    # -- 1. valid permutation ------------------------------------------------
    print("=== 1. permutation validity ===")
    for q in range(2, 9):
        n = 1 << q
        masks = [1 << k for k in range(q)]
        perm = order(n, masks, time_budget_s=60.0)
        check(f"q={q} perm is a permutation of range({n})",
              sorted(perm) == list(range(n)))
    # a non-hypercube family too (irregular mask set)
    _m = [1, 2, 5, 6, 11]
    _perm = order(64, _m, time_budget_s=60.0)
    check("irregular masks n=64 perm valid", sorted(_perm) == list(range(64)))

    # -- 2. round-trip: harness reproduces AMD's internal ops ----------------
    print()
    print("=== 2. round-trip vs harness.eliminate_with_perm ===")
    for q in range(2, 10):
        n = 1 << q
        masks = [1 << k for k in range(q)]
        perm, ops, maxd, done, steps = order_with_stats(n, masks, time_budget_s=120.0)
        assert done, f"AMD ran out of budget at q={q}"
        h_fill, h_ops, h_maxd, h_done, _ = eliminate_with_perm(n, masks, perm, time_budget_s=300.0)
        check(f"q={q} ops match ({ops} == {h_ops}) and max_deg match ({maxd} == {h_maxd})",
              h_done and ops == h_ops and maxd == h_maxd)
    perm, ops, maxd, done, _ = order_with_stats(64, _m, time_budget_s=120.0)
    h_fill, h_ops, h_maxd, h_done, _ = eliminate_with_perm(64, _m, perm, time_budget_s=300.0)
    check(f"irregular masks ops match ({ops} == {h_ops})",
          done and h_done and ops == h_ops and maxd == h_maxd)

    # -- 3. AMD vs exact minimum degree, hypercube q=4..9 --------------------
    print()
    print("=== 3. AMD vs exact min-degree, hypercube Q_q ===")
    print(f"{'q':>3} {'n':>6} {'amd_ops':>14} {'md_ops':>14} {'ratio':>8} "
          f"{'amd_fill':>12} {'md_fill':>12} {'amd/n^3':>9} {'md/n^3':>9}")
    for q in range(4, 10):
        n = 1 << q
        masks = [1 << k for k in range(q)]
        perm, a_ops, a_maxd, a_done, _ = order_with_stats(n, masks, time_budget_s=120.0)
        a_fill, a_ops_h, _, a_done_h, _ = eliminate_with_perm(n, masks, perm, time_budget_s=300.0)
        m_fill, m_ops, m_maxd, m_done, _ = min_degree_fill(n, masks, time_budget_s=300.0)
        assert a_done and a_done_h and m_done, f"budget exhausted at q={q}"
        ratio = a_ops / m_ops
        print(f"{q:>3} {n:>6} {a_ops:>14} {m_ops:>14} {ratio:>8.4f} "
              f"{a_fill:>12} {m_fill:>12} {a_ops / n**3:>9.5f} {m_ops / n**3:>9.5f}")
        check(f"q={q} AMD/min-degree ops ratio {ratio:.4f} within factor 3",
              1.0 / 3.0 <= ratio <= 3.0)

    print()
    print("ALL PASS" if ok else "SOME CHECKS FAILED")
    raise SystemExit(0 if ok else 1)
