"""Spectral (Fiedler-vector) elimination ordering for certkit-cpo.

Contract: NAME, order(n, masks, time_budget_s=120.0) -> permutation of range(n).

HOW IT WORKS
------------
The Laplacian of the Cayley graph on Z_2^q generated by `masks` never needs to
be stored:

    (Lx)[i] = deg * x[i] - sum_m x[i ^ m],      deg = |distinct nonzero masks|

which is O(n*|masks|) per matvec.  The Fiedler vector is obtained by power
iteration on B = (2*deg)*I - L with the constant vector re-projected out every
step: on a connected graph the constant vector is the exact null eigenvector,
so deflating it leaves the Fiedler vector as B's dominant one.  Convergence is
measured by the true residual ||Lx - lambda x|| and is REPORTED, never assumed
(see LAST_INFO and the `converged` flag) -- an unconverged vector would silently
corrupt the ordering.

THE CLOSED-FORM SPECTRUM, AND WHY SPECTRAL ORDERING CANNOT HELP HERE
--------------------------------------------------------------------
On a Cayley graph over Z_2^q the Laplacian eigenvectors are exactly the
Walsh-Hadamard characters

    chi_s(i) = (-1)^popcount(i & s),   s = 0..n-1

with eigenvalue  lambda_s = sum_m (1 - (-1)^popcount(m & s)) = 2 * |{m : <m,s> odd}|.

So the whole spectrum is available in closed form in O(n*|masks|), with no
iteration at all.  self-check #2/#3 below verify this against the matvec and
against the power iteration.

The consequence is a real, negative result about this graph family, stated here
rather than hidden:

  * Every Fiedler vector is a +-1 vector (a character, or -- under degeneracy --
    a real combination of characters).  It takes only |{lambda_s = lambda_2}|
    distinct-ish values, never a smooth coordinate.
  * For the PURE HYPERCUBE Q_q (masks = {1,2,4,...}) lambda_s = 2*popcount(s),
    so the Fiedler eigenvalue 2 has multiplicity exactly q, spanned by the q
    single-bit characters chi_{2^k}(i) = (-1)^{bit_k(i)}.  Any vector in that
    eigenspace is i -> sum_k c_k (-1)^{bit_k(i)}, i.e. a WEIGHTED LINEAR
    FUNCTION OF THE BITS.  Sorting by it therefore degenerates to sorting by a
    weighted Hamming weight -- and for a single character (c supported on one
    bit) literally to "sort by one bit", a 2-way split with no recursion.
  * That is precisely the split the session-6 middle-layer analysis already
    covers: the top-level separator is the middle Hamming layer, ~n/sqrt(q)
    wide, and the halves are again hypercubes.  Spectral bisection recovers the
    known-optimal cut and no better one, so it cannot beat -- or even change the
    asymptotics of -- what min-degree already measured.

Self-check #5 verifies this numerically rather than asserting it: the converged
Q_q Fiedler vector matches sum_k c_k*chi_{2^k} to ~1e-12, and re-sorting by that
bit-weight functional alone reproduces order()'s permutation exactly.

DISCONNECTED FAMILIES: the Cayley graph is connected iff the masks span Z_2^q.
If they do not, lambda_2 = 0 and the "Fiedler vector" is an arbitrary member of
a >=2-dimensional null space, i.e. meaningless.  order() detects this with a
GF(2) rank of the masks and falls back to ordering component-by-component
(which is the optimal separation there anyway: an empty separator).  The
fallback is recorded in LAST_INFO.

The solver itself is fine; self-check #4 is a positive control on a 1D path,
where it recovers the exact cosine mode and the monotone path order.  The
degeneracy above is a fact about the hypercube, not about the solver.
"""
import math
import random
import time

NAME = "spectral (Fiedler)"

# quantization used only for deterministic tie-breaking, relative to max|v|
_TIE_QUANT = 1e-6

# populated by the last fiedler_* call; inspected by the harness / self-check
LAST_INFO = {}


# ---------------------------------------------------------------- matvecs

def _clean_masks(masks):
    return sorted({m for m in masks if m})


def make_matvec_masks(n, masks):
    """L*x for the Cayley graph on Z_2^q generated by `masks`."""
    ms = _clean_masks(masks)
    deg = len(ms)

    def mv(x):
        out = [0.0] * n
        for i in range(n):
            s = 0.0
            for m in ms:
                s += x[i ^ m]
            out[i] = deg * x[i] - s
        return out

    return mv, deg


def make_matvec_adj(adj):
    """L*x for an explicit adjacency list (helper for non-Cayley controls)."""
    n = len(adj)
    nbrs = [tuple(a) for a in adj]
    deg_max = max((len(a) for a in nbrs), default=0)

    def mv(x):
        out = [0.0] * n
        for i in range(n):
            s = 0.0
            for j in nbrs[i]:
                s += x[j]
            out[i] = len(nbrs[i]) * x[i] - s
        return out

    return mv, deg_max


# ------------------------------------------------------- closed-form spectrum

def closed_form_spectrum(n, masks):
    """lambda_s for every character s, in O(n*|masks|). Index = s."""
    ms = _clean_masks(masks)
    return [sum(1 - (-1) ** ((m & s).bit_count()) for m in ms) for s in range(n)]


def character(n, s):
    return [1.0 if (i & s).bit_count() % 2 == 0 else -1.0 for i in range(n)]


def closed_form_fiedler_value(n, masks):
    """Second-smallest Laplacian eigenvalue (0 if the graph is disconnected)."""
    ev = sorted(closed_form_spectrum(n, masks))
    return ev[1] if n > 1 else 0.0


def component_labels(n, masks):
    """(labels, n_components) for the Cayley graph.

    The component of i is the coset i XOR span(masks), so a GF(2) row reduction
    of the masks gives the label of every vertex in O(n*rank).  n_components =
    n / 2^rank; the graph is connected iff the masks span Z_2^q.
    """
    piv = {}            # leading bit -> basis vector with that leading bit

    def reduce(v):
        # descending pivots: XOR can only touch strictly lower bits, so one
        # pass yields the canonical coset representative
        for p in sorted(piv, reverse=True):
            if v >> p & 1:
                v ^= piv[p]
        return v

    for m in _clean_masks(masks):
        v = reduce(m)
        if v:
            piv[v.bit_length() - 1] = v
    labels = [reduce(i) for i in range(n)]
    return labels, n >> len(piv)


# -------------------------------------------------------- power iteration

def _fiedler(mv, deg_max, n, tol=1e-9, max_iter=200000, seed=0,
             time_budget_s=120.0):
    """Shifted power iteration on B = 2*deg_max*I - L, constant deflated.

    Returns (vec, lam, converged, iters, residual).
    """
    shift = 2.0 * deg_max if deg_max else 1.0
    rng = random.Random(seed)
    x = [rng.uniform(-1.0, 1.0) for _ in range(n)]

    def deflate_normalize(v):
        mean = math.fsum(v) / n
        v = [a - mean for a in v]
        nrm = math.sqrt(math.fsum(a * a for a in v))
        if nrm == 0.0:
            return None
        return [a / nrm for a in v]

    x = deflate_normalize(x)
    t0 = time.time()
    lam = 0.0
    res = float("inf")
    it = 0
    converged = False
    while it < max_iter:
        it += 1
        Lx = mv(x)
        # Rayleigh quotient (x is unit norm)
        lam = math.fsum(x[i] * Lx[i] for i in range(n))
        res = math.sqrt(math.fsum((Lx[i] - lam * x[i]) ** 2 for i in range(n)))
        if res <= tol:
            converged = True
            break
        if time.time() - t0 > time_budget_s:
            break
        y = deflate_normalize([shift * x[i] - Lx[i] for i in range(n)])
        if y is None:
            break
        x = y
    LAST_INFO.clear()
    LAST_INFO.update(n=n, lam=lam, residual=res, iters=it, converged=converged,
                     shift=shift, tol=tol)
    return x, lam, converged, it, res


def fiedler_from_masks(n, masks, tol=1e-9, max_iter=200000, seed=0,
                       time_budget_s=120.0):
    mv, deg = make_matvec_masks(n, masks)
    return _fiedler(mv, deg, n, tol, max_iter, seed, time_budget_s)


def fiedler_from_adj(adj, tol=1e-9, max_iter=200000, seed=0,
                     time_budget_s=120.0):
    mv, deg_max = make_matvec_adj(adj)
    return _fiedler(mv, deg_max, len(adj), tol, max_iter, seed, time_budget_s)


# ------------------------------------------------------------- the ordering

def _perm_from_vec(vec):
    n = len(vec)
    scale = max((abs(v) for v in vec), default=0.0)
    q = _TIE_QUANT * scale if scale > 0 else 1.0
    return sorted(range(n), key=lambda i: (round(vec[i] / q), i))


def order(n, masks, time_budget_s=120.0):
    """Vertices ascending by Fiedler value, ties broken by index.

    Convergence is recorded in LAST_INFO['converged']; on the hypercube the
    result is degenerate by construction (see module docstring).
    """
    labels, ncomp = component_labels(n, masks)
    if ncomp > 1:
        # Disconnected (the masks do not span Z_2^q): lambda_2 = 0 and the
        # "Fiedler vector" is an arbitrary vector of the >=2-dimensional null
        # space, so power iteration says nothing useful.  Order component by
        # component instead -- that IS the optimal top-level separation here
        # (empty separator).
        # ponytail: no recursive spectral bisection inside each component;
        # add it if a disconnected family ever shows up in the real sweep.
        LAST_INFO.clear()
        LAST_INFO.update(n=n, components=ncomp, converged=True,
                         note="disconnected: ordered by component, then index")
        return sorted(range(n), key=lambda i: (labels[i], i))
    vec, _lam, _conv, _it, _res = fiedler_from_masks(
        n, masks, time_budget_s=time_budget_s)
    LAST_INFO["components"] = 1
    return _perm_from_vec(vec)


def order_from_adj(adj, time_budget_s=120.0):
    vec, _lam, _conv, _it, _res = fiedler_from_adj(
        adj, time_budget_s=time_budget_s)
    return _perm_from_vec(vec)


# ------------------------------------------------------------------ checks

def _path_adj(n):
    adj = [set() for _ in range(n)]
    for i in range(n - 1):
        adj[i].add(i + 1)
        adj[i + 1].add(i)
    return adj


def _mask_sets():
    return [
        ("hypercube q=3", 3, [1, 2, 4]),
        ("hypercube q=5", 5, [1 << k for k in range(5)]),
        ("hypercube q=8", 8, [1 << k for k in range(8)]),
        ("q=6 pairs", 6, [3, 6, 12, 24, 48, 33]),          # disconnected
        ("q=7 mixed", 7, [1, 2, 4, 8, 16, 32, 64, 5, 27, 96]),
        ("q=8 sparse", 8, [1, 6, 40, 129]),                 # disconnected
        ("q=6 spanning", 6, [1, 2, 4, 8, 16, 32, 3, 5]),
    ]


if __name__ == "__main__":
    fails = 0

    def check(cond, msg):
        global fails
        print(("PASS: " if cond else "FAIL: ") + msg)
        if not cond:
            fails += 1

    print("=== 1. order() returns a valid permutation ===")
    perms = {}
    for label, q, masks in _mask_sets():
        n = 1 << q
        p = order(n, masks, time_budget_s=30.0)
        perms[label] = p
        check(sorted(p) == list(range(n)),
              f"{label}: permutation of range({n}) "
              f"(components={LAST_INFO.get('components')}, "
              f"converged={LAST_INFO.get('converged')}, "
              f"iters={LAST_INFO.get('iters', '-')})")

    print()
    print("=== 1b. order() is not a masks-ignoring stub ===")
    # A module that returned range(n) (or any fixed perm) would pass check 1
    # above; these two kill that mutant.
    for label, q, masks in _mask_sets():
        n = 1 << q
        if component_labels(n, masks)[1] == 1:   # connected: must be non-trivial
            check(perms[label] != list(range(n)),
                  f"{label}: order() != range(n) (it actually used the spectrum)")
    a = order(256, [1 << k for k in range(8)], 30.0)
    b = order(256, [1, 2, 4, 8, 16, 32, 64, 128, 3, 21], 30.0)
    check(a != b, "order() output changes when `masks` changes (q=8, two mask sets)")

    print()
    print("=== 1c. disconnected fallback really blocks by component ===")
    # With component detection removed, power iteration returns an arbitrary
    # null vector and the order interleaves components; check 1 would not
    # notice.  Require every component to occupy a contiguous run.
    for label, q, masks in _mask_sets():
        n = 1 << q
        labels, ncomp = component_labels(n, masks)
        if ncomp == 1:
            continue
        seq = [labels[i] for i in perms[label]]
        runs = 1 + sum(1 for i in range(1, n) if seq[i] != seq[i - 1])
        check(runs == ncomp,
              f"{label}: all {ncomp} components contiguous in the order "
              f"(runs={runs})")

    print()
    print("=== 1d. negative control: `converged` is not hard-wired True ===")
    # Starve the solver; if it still claims convergence, every `check(conv,...)`
    # below is vacuous.
    _v, _l, conv_starved, it_s, res_s = fiedler_from_adj(
        _path_adj(64), tol=1e-12, max_iter=5, time_budget_s=60.0)
    check(conv_starved is False and LAST_INFO["converged"] is False,
          f"max_iter=5 on a slow graph reports converged=False "
          f"(iters={it_s}, residual={res_s:.2e})")
    _v, _l, conv_timed, _i, _r = fiedler_from_adj(
        _path_adj(64), tol=1e-12, max_iter=10 ** 9, time_budget_s=0.001)
    check(conv_timed is False, "an exhausted time budget reports converged=False")

    print()
    print("=== 2. Walsh characters are exact eigenpairs (L*chi = lam*chi) ===")
    for label, q, masks in _mask_sets():
        n = 1 << q
        mv, _deg = make_matvec_masks(n, masks)
        spec = closed_form_spectrum(n, masks)
        worst = 0.0
        for s in range(n):
            chi = character(n, s)
            Lc = mv(chi)
            lam = spec[s]
            worst = max(worst, max(abs(Lc[i] - lam * chi[i]) for i in range(n)))
        check(worst < 1e-9, f"{label}: max |L*chi - lam*chi| = {worst:.3e} over all {n} characters")

    print()
    print("=== 3. power-iteration Fiedler value vs closed form (tol 1e-6) ===")
    print(f"{'family':>16} {'ncomp':>6} {'lam_power':>14} {'lam_exact':>14} {'|diff|':>10} {'iters':>7} {'resid':>10} {'conv':>6}")
    for label, q, masks in _mask_sets():
        n = 1 << q
        _v, lam, conv, it, res = fiedler_from_masks(
            n, masks, tol=1e-10, max_iter=200000, time_budget_s=60.0)
        exact = closed_form_fiedler_value(n, masks)
        ncomp = component_labels(n, masks)[1]
        print(f"{label:>16} {ncomp:>6} {lam:>14.10f} {exact:>14.10f} {abs(lam-exact):>10.2e} "
              f"{it:>7} {res:>10.2e} {str(conv):>6}")
        check(conv and abs(lam - exact) < 1e-6,
              f"{label}: Fiedler eigenvalue matches closed form to 1e-6"
              + ("  [disconnected: lambda_2 = 0, order() falls back to component order]"
                 if ncomp > 1 else ""))
        check((ncomp > 1) == (exact == 0),
              f"{label}: closed-form lambda_2 == 0 iff masks fail to span Z_2^{q} "
              f"(ncomp={ncomp})")

    print()
    print("=== 4. positive control: 1D path graph ===")
    for n in [16, 32, 64]:
        adj = _path_adj(n)
        vec, lam, conv, it, res = fiedler_from_adj(
            adj, tol=1e-9, max_iter=400000, time_budget_s=60.0)
        exact = 2.0 - 2.0 * math.cos(math.pi / n)
        p = order_from_adj(adj, time_budget_s=60.0)
        ok_perm = (p == list(range(n)) or p == list(reversed(range(n))))
        # known cosine mode, up to sign/scale
        cos_mode = [math.cos(math.pi * (i + 0.5) / n) for i in range(n)]
        cn = math.sqrt(math.fsum(c * c for c in cos_mode))
        cos_mode = [c / cn for c in cos_mode]
        dot = abs(math.fsum(vec[i] * cos_mode[i] for i in range(n)))
        print(f"  n={n:>3}  lam={lam:.10f} exact={exact:.10f}  |<v,cos>|={dot:.10f}  iters={it} resid={res:.2e}")
        check(conv, f"path n={n}: power iteration converged")
        check(abs(lam - exact) < 1e-7, f"path n={n}: Fiedler eigenvalue = cosine mode eigenvalue")
        check(abs(dot - 1.0) < 1e-6, f"path n={n}: Fiedler vector IS the cosine mode (|<v,cos>|=1)")
        check(ok_perm, f"path n={n}: spectral ordering recovers monotone path order (up to reversal)")

    print()
    print("=== 5. reported finding: hypercube Fiedler degeneracy ===")
    for q in [4, 6, 8]:
        n = 1 << q
        spec = closed_form_spectrum(n, [1 << k for k in range(q)])
        lam2 = closed_form_fiedler_value(n, [1 << k for k in range(q)])
        mult = sum(1 for e in spec if e == lam2)
        print(f"  Q_{q}: lambda_2 = {lam2}, multiplicity = {mult} (= q), "
              f"eigenspace = span of the q single-bit characters")
        check(mult == q, f"Q_{q}: Fiedler eigenspace has dimension q -> ordering is a weighted bit sum, not a smooth cut")
    # the converged vector must lie ENTIRELY in span{chi_{2^k}}, i.e. it is a
    # weighted bit sum -- so the spectral order is a linear-threshold order on
    # the bits, never a smooth multi-scale cut.
    for q in [4, 6, 8]:
        n = 1 << q
        hyp = [1 << k for k in range(q)]
        vec, _lam, conv, _it, _res = fiedler_from_masks(n, hyp, tol=1e-11,
                                                        time_budget_s=60.0)
        c = [math.fsum(vec[i] * ((-1.0) ** ((i >> k) & 1)) for i in range(n)) / n
             for k in range(q)]
        recon = [math.fsum(c[k] * ((-1.0) ** ((i >> k) & 1)) for k in range(q))
                 for i in range(n)]
        err = max(abs(vec[i] - recon[i]) for i in range(n))
        perm = _perm_from_vec(vec)
        perm_lin = sorted(range(n), key=lambda i: (round(recon[i] / (_TIE_QUANT * max(map(abs, recon)))), i))
        print(f"  Q_{q}: || v - sum_k c_k*chi_bit_k ||_inf = {err:.2e}; "
              f"c = [" + ", ".join(f"{x:+.4f}" for x in c) + "]")
        check(conv and err < 1e-7,
              f"Q_{q}: Fiedler vector is EXACTLY a weighted bit sum -> "
              f"spectral order == sort by a weighted Hamming weight")
        check(perm == perm_lin, f"Q_{q}: spectral order reproduced by the bit-weight functional alone")

    print()
    print(f"{'ALL CHECKS PASSED' if fails == 0 else str(fails) + ' CHECK(S) FAILED'}")
    raise SystemExit(1 if fails else 0)
