"""
certkit-cpo sweep driver: every ordering x every mask family x >=3 doublings of n.

Prints one row per (ordering, family, q) with fill edges, the ops/n^3 proxy, and
whether the cell completed within its time budget. Partial cells are reported as
partial -- never silently averaged in.

Run:  uv run python run_sweep.py [--max-q 11] [--budget 300] [--only ordering,...]
"""
import argparse
import json
import sys
import time

import harness
import families

import ord_rcm
import ord_nd
import ord_amd
import ord_spectral

# min-degree is not a static perm; it lives in harness. Treat it as an ordering
# with the same interface by wrapping it.
ORDERINGS = [
    ("natural", None),          # baseline: index order, no reordering at all
    ("min_degree", "builtin"),  # session-6 anchor
    ("amd", ord_amd),
    ("rcm", ord_rcm),
    ("nested_dissection", ord_nd),
    ("spectral", ord_spectral),
]


def n_components(q, masks):
    """Number of connected components of the Cayley graph on Z_2^q generated by
    `masks`: exactly 2^(q - rank), where rank is the GF(2) rank of the mask set
    (the graph's components are the cosets of the subgroup the masks span).

    This matters a great deal for the headline number. Most physically-motivated
    mask families (any family whose terms all have EVEN bit-flip weight -- 1D/2D
    XX chains, all-to-all, JW/BK) span only the even-weight subgroup, so the
    operator is block-diagonal in 2 parity sectors. Elimination never creates an
    edge between components, so ops = sum of per-sector ops, and comparing that
    against a single dense n^3 hands the ordering a free factor of c^2 that has
    nothing to do with fill reduction. The honest comparison is against the cost
    of dense-factorising each sector: c * (n/c)^3 = n^3 / c^2.
    """
    basis = []
    for m in masks:
        v = m
        for b in basis:
            v = min(v, v ^ b)
        if v:
            basis.append(v)
            basis.sort(reverse=True)
    return 1 << (q - len(basis))


def run_cell(ordering, mod, n, masks, budget):
    """-> dict with fill/ops/max_deg/completed/secs, or None on hard failure."""
    t0 = time.time()
    try:
        if mod == "builtin":
            fill, ops, maxd, done, steps = harness.min_degree_fill(
                n, masks, time_budget_s=budget
            )
        else:
            if mod is None:
                perm = list(range(n))
            else:
                perm = mod.order(n, masks, time_budget_s=budget)
                if sorted(perm) != list(range(n)):
                    return {"error": "not a permutation"}
            fill, ops, maxd, done, steps = harness.eliminate_with_perm(
                n, masks, perm, time_budget_s=budget
            )
    except Exception as exc:  # a broken ordering must not kill the whole sweep
        return {"error": f"{type(exc).__name__}: {exc}"}
    return {
        "fill": fill,
        "ops": ops,
        "max_deg": maxd,
        "completed": done,
        "steps": steps,
        "secs": time.time() - t0,
        "ops_over_n3": ops / n**3,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--min-q", type=int, default=8)
    ap.add_argument("--max-q", type=int, default=11)
    ap.add_argument("--budget", type=float, default=300.0)
    ap.add_argument("--only", default="", help="comma-separated ordering names")
    ap.add_argument("--families", default="", help="comma-separated family names")
    ap.add_argument("--json-out", default="")
    args = ap.parse_args()

    orderings = ORDERINGS
    if args.only:
        want = set(args.only.split(","))
        orderings = [o for o in orderings if o[0] in want]
    fam_names = list(families.FAMILIES)
    if args.families:
        want = set(args.families.split(","))
        fam_names = [f for f in fam_names if f in want]

    qs = list(range(args.min_q, args.max_q + 1))
    rows = []

    hdr = (f"{'ordering':>18} {'family':>16} {'q':>3} {'n':>6} {'#masks':>7} "
           f"{'comp':>4} {'fill_edges':>12} {'op_proxy':>15} {'max_deg':>8} "
           f"{'ops/n^3':>9} {'ops/sector':>10} {'secs':>7} {'status':>9}")
    print(hdr)
    print("-" * len(hdr))
    for oname, mod in orderings:
        for fam in fam_names:
            for q in qs:
                try:
                    n, masks = families.FAMILIES[fam](q)
                except Exception as exc:
                    print(f"{oname:>18} {fam:>16} {q:>3}  family error: {exc}")
                    continue
                if not masks:
                    continue
                c = n_components(q, masks)
                r = run_cell(oname, mod, n, masks, args.budget)
                if "error" not in r:
                    # fair baseline: dense-factorise each sector, c*(n/c)^3 = n^3/c^2
                    r["ops_over_sector"] = r["ops"] * c * c / n**3
                rec = {"ordering": oname, "family": fam, "q": q, "n": n,
                       "n_masks": len(masks), "n_components": c, **r}
                rows.append(rec)
                if "error" in r:
                    print(f"{oname:>18} {fam:>16} {q:>3} {n:>6} {len(masks):>7} "
                          f"{c:>4}   ERROR: {r['error']}")
                else:
                    status = "ok" if r["completed"] else f"part{r['steps']}"
                    print(f"{oname:>18} {fam:>16} {q:>3} {n:>6} {len(masks):>7} "
                          f"{c:>4} {r['fill']:>12} {r['ops']:>15} {r['max_deg']:>8} "
                          f"{r['ops_over_n3']:>9.5f} {r['ops_over_sector']:>10.5f} "
                          f"{r['secs']:>7.1f} {status:>9}")
                sys.stdout.flush()

    if args.json_out:
        with open(args.json_out, "w") as fh:
            json.dump(rows, fh, indent=1)
        print(f"\nwrote {len(rows)} rows to {args.json_out}")


if __name__ == "__main__":
    main()
